language: cpp

os:
    - linux

env:
    - CONFIG=Release
    - CONFIG=Debug

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt54
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.9 libc6-i386 qt54tools qt54svg qt54webkit
    - sudo apt-get install flashplugin-installer
    - export CXX="g++-4.9"
    - export CC="gcc-4.9";
    - source /opt/qt54/bin/qt54-env.sh;

script:
    # make sure the app can be build and installed without errors
    - qmake
    - make
    - sudo make install

    # a few functional test
    - MellowPlayer --service=deezer --autoquit-delay=10
    - MellowPlayer --service=grooveshark --autoquit-delay=10
    - MellowPlayer --service=groovesharkmobile --autoquit-delay=10
    - MellowPlayer --service=mixcloud --autoquit-delay=10
