language: cpp

os:
    - linux

env:
    - CONFIG=Release
    - CONFIG=Debug

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt551
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.9 libc6-i386 qt55tools qt55svg qt55webengine
    # require ubuntu 14.04 -> Semaphore CI?
    - sudo apt-get install pepperflashplugin-nonfree
    - sudo update-pepperflashplugin-nonfree --install
    - export CXX="g++-4.9"
    - export CC="gcc-4.9";
    - source /opt/qt55/bin/qt55-env.sh;

script:
    # make sure the app can be build and installed without errors
    - qmake
    - make
    - sudo make install

    # a few functional test
    - mellowplayer --service=deezer --autoquit-delay=10
    - mellowplayer --service=spotify --autoquit-delay=10
    - mellowplayer --service=mixcloud --autoquit-delay=10
    - mellowplayer --service=soundcloud --autoquit-delay=10

