language: cpp

os:
    - linux

env:
    - CONFIG=Release
    - CONFIG=Debug

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
    # install qt5.6 beta from a tar.gz archive hosted on my dropbox
    # this build already contains snorenotify
    - wget https://www.dropbox.com/s/q02ekria8pj72hs/Qt5.6.0.tar.gz
    - tar -zxf Qt5.6.0.tar.gz

script:
    # make sure the app can be build and installed without errors
    - Qt5.6.0/5.6/gcc_64/bin/qmake
    - make
    - sudo make install
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/Qt5.6.0/5.6/gcc_64/lib:$PWD/Qt5.6.0/5.6/gcc_64/lib64

    # a few functional tests
    - mellowplayer --service=deezer --autoquit-delay=10
    - mellowplayer --service=spotify --autoquit-delay=10
    - mellowplayer --service=mixcloud --autoquit-delay=10
    - mellowplayer --service=soundcloud --autoquit-delay=10
    - mellowplayer --service=deezer --standalone --autoquit-delay=10
    - mellowplayer --service=spotify --standalone --autoquit-delay=10
    - mellowplayer --service=mixcloud --standalone --autoquit-delay=10
    - mellowplayer --service=soundcloud --standalone --autoquit-delay=10

